-- ============================================================
-- OBSOLÈTE — Ce fichier a été remplacé par schema-bibliotheque.sql (v3)
-- ============================================================
-- L'ancien fix recréait des policies avec des jointures croisées
-- entre ressources et ressources_partages, causant une boucle infinie.
--
-- → Exécute schema-bibliotheque.sql à la place.
--   Il DROP les anciennes policies et les recrée avec des fonctions
--   SECURITY DEFINER qui cassent la récursion.
-- ============================================================
